---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pds-config
  labels:
    app.kubernetes.io/component: atproto-pds
    app.kubernetes.io/name: atproto
data:
  PDS_HOSTNAME: "pds-hostname"
  PDS_DATA_DIRECTORY: "/data"
  PDS_BLOBSTORE_DISK_LOCATION: "/data/blocks"
  PDS_DID_PLC_URL: "https://plc.directory"
  PDS_BSKY_APP_VIEW_URL: "https://api.bsky.app"
  PDS_BSKY_APP_VIEW_DID: "did:web:api.bsky.app"
  PDS_REPORT_SERVICE_URL: "https://mod.bsky.app"
  PDS_REPORT_SERVICE_DID: "did:plc:ar7c4by46qjdydhdevvrndac"
  PDS_CRAWLERS: "https://bsky.network"
  LOG_ENABLED: "true"
