---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pds-data
  labels:
    app.kubernetes.io/component: atproto-pds
    app.kubernetes.io/name: atproto
spec:
  # Your storage class may not have ReadWriteMany.
  # If it does not, setting it to ReadWriteOnce is fine.
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
