---
apiVersion: v1
kind: Service
metadata:
  name: pds
  labels:
    app.kubernetes.io/component: atproto-pds
    app.kubernetes.io/name: atproto
spec:
  ports:
  - port: 80
    targetPort: 2583
    name: http
  selector:
    app: pds
  type: ClusterIP
